title: Aussie Add-ons
tagline: Kodi repository of add-ons for Australian content.
url: https://aussieaddons.com
giturl: http://aussieaddons.github.io
baseurl:
rss: https://aussieaddons.com/atom.xml

# Dependencies
markdown: kramdown

author:
  name: Aussie Addons
  email: aussieaddons@aussieaddons.com
  github: aussieaddons
  twitter: aussieaddons


exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

collections:
  addons:
    output: true
    permalink: /addons/:path/

analytics:
  tracking_id: 'UA-97650894-1'

exclude:
 - vendor

plugins:
  - jekyll-paginate
  - jekyll-feed
